### PR TITLE
issue/13 – Allow rejected referrals to be completed via complete_referral()

### PR DESCRIPTION
**Pull request by DrewAPicture**
Issue #13

**Housekeeping**

* [x] Issue number has been linked below the description
* [x] Branch name follows the `issue/###` or `release/###` format
* [x] PR title is prefixed with the branch name (issue/### - Title)

**Proposed changes**

* [ ] Code has been tested with no errors
* [x] Code meets stated minimum requirements
* [x] Code should (usually) not contain unrelated changes
* [x] Code style (including docs) and organization is generally consistent with the rest of the codebase
* [x] Before and after screenshots have been posted to document visual changes
* [ ] Clear steps for testing the PR have been posted (as needed)

### CODE REVIEW

**Comment by DrewAPicture** [comment]
At this point this is just a theory for how to solve this problem. In _theory_, a rejected referral should be able to complete here whereas a pending one will not, thereby continuing to be forced pending.

**Comment by tjackson1317** [comment]
Moving this comment here:

Was able to test the `issue/13` branch today, which does update the referral status automatically after the failed order is completed. However, I did find that it updates referrals to _Unpaid_, rather than to _Pending_.

**Comment by DrewAPicture** [comment]
OK, so yeah, we're about halfway there. The change is actually happening in core, let me see if there's a way we can force the status to be `pending` from the add-on side.

**Comment by tjackson1317** [comment]
@DrewAPicture Haven't heard back from the customer yet, but FYI this worked beautifully in my own tests! ✨

(Sorry I keep meaning to comment here the 1st time lol)

**Comment by DrewAPicture** [comment]
We're taking the customer's silence as acceptance of the fix.

**Pull request merged**
